const test=require('node:test'),assert=require('node:assert/strict'),C=require('../scripts/portfolio_conviction');
const now=Date.parse('2026-09-23T02:00:00Z'),p={symbol:'2330.TW',market:'TW'},a={status:'hold',checks:Array.from({length:5},()=>({passed:true}))};
test('stars never override risk, missing data or overheating',()=>{assert.match(C.advice(5,{status:'exit'}),/先處理風險/);assert.match(C.advice(5,{status:'unknown'}),/先補齊/);assert.match(C.advice(5,{status:'trim',hot:true}),/先不追買/);assert.match(C.advice(5,a),/待評估方案/);});
test('forecast locks explicit revenue target, subjective rank and method version',()=>{const f=C.make({stars:4,months:2,comparison:'yoy',criterion:'Revenue YoY above zero',thesis:'Orders',invalidates:'Delay'},p,a,now);assert.equal(f.targetMonth,'2026-11');assert.equal(f.targetAfter,'2026-12-01T00:00:00.000Z');assert.equal(f.oneWayCost,.003);assert.equal(f.probability,undefined);assert.throws(()=>C.make({stars:6,months:2},p,a,now));});
const f={symbol:'2330.TW',market:'TW',createdAt:'2026-09-23T02:00:00Z',targetAfter:'2026-10-01T00:00:00Z',oneWayCost:.003};
const prices={markets:{TW:{dates:['2026-09-23','2026-09-24','2026-09-30']}},stocks:{'2330.TW':{market:'TW',bars:[['2026-09-23',90,100],['2026-09-24',110,100],['2026-09-30',120,121]]}}};
test('forward proxy begins after recording, at next open, and waits until target maturity',()=>{assert.equal(C.forward(f,prices,now).status,'pending');const x=C.forward(f,prices,Date.parse('2026-10-02'));assert.equal(x.entry,'2026-09-24');assert.equal(x.exit,'2026-09-30');assert.ok(Math.abs(x.returnPct-((121*.997/(110*1.003)-1)*100))<1e-8);assert.ok(x.doubleCost<x.returnPct);});
test('missing sessions or pruned entry cannot be silently filled',()=>{const d=structuredClone(prices);d.stocks['2330.TW'].bars.splice(1,1);assert.equal(C.forward(f,d,Date.parse('2026-10-02')).status,'missing');d.markets.TW.dates=['2026-09-30'];assert.equal(C.forward(f,d,Date.parse('2026-10-02')).status,'missing');});
test('revenue hit and profitable price trade are separate outcomes',()=>{assert.equal(C.revenue({actualRevenue:110,baselineRevenue:100,sourceUrl:'https://example.com'}).hit,true);assert.throws(()=>C.revenue({actualRevenue:1,baselineRevenue:0,sourceUrl:'https://example.com'}));});
test('custom hypotheses keep explicit judgments while blank revenue cannot become zero',()=>{
 assert.deepEqual(C.revenue({kind:'custom',hit:false,note:'Target missed',sourceUrl:'https://example.com'}),{hit:false,growthPct:null});
 assert.throws(()=>C.revenue({kind:'custom',hit:true,note:'',sourceUrl:'https://example.com'}));
 for(const actualRevenue of ['',null,undefined])assert.throws(()=>C.revenue({actualRevenue,baselineRevenue:100,sourceUrl:'https://example.com'}));
});
test('revisions do not inflate calibration, earliest rating stays in its original bin',()=>{const rows=[{...f,stars:5,targetMonth:'2026-09',comparison:'yoy',createdAt:'2026-09-24',outcome:{actualRevenue:110,baselineRevenue:100,sourceUrl:'https://example.com'}},{...f,stars:3,targetMonth:'2026-09',comparison:'yoy'}];const stats=C.summarize(rows,prices,now);assert.equal(stats[2].forecasts,1);assert.equal(stats[4].forecasts,0);assert.equal(stats[2].revenueSamples,0);});
